#!/bin/bash

rm -f gitlab-data/runner/config.toml
docker-compose down

if [ "$MINARD_BACKEND_ECR" = "" ]
then
   docker-compose up
else
   echo "Using images from ECR"
   docker-compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose-ecr.yml up
fi
