# Based on https://github.com/sameersbn/docker-gitlab/blob/master/docker-compose.yml
# The main changes are mounting the directories under ./gitlab-data and
# including gitlab-runner and charles

version: '2'

services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    ports:
    - "16379:6379"
    command:
    - --loglevel warning

  postgresql:
    restart: always
    image: postgres:9.5
    ports:
    - "15432:5432"
    environment:
    - PGDATA=/var/lib/postgresql/data/pgdata
    - POSTGRES_USER=gitlab
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=gitlabhq_production

  gitlab:
    restart: always
    image: 366857391347.dkr.ecr.eu-west-1.amazonaws.com/gitlab:20_469487
    depends_on:
    - redis
    - postgresql
    ports:
    - "10080:80"
    - "10022:22"
    environment:
    - DEBUG=false
    - MINARD_CI_YML_URL=http://charles:8000/ci/projects/%d/%s/%s/yml
    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production

    - REDIS_HOST=redis
    - REDIS_PORT=6379

    - TZ=Asia/Kolkata
    - GITLAB_TIMEZONE=Kolkata

    - GITLAB_HTTPS=false
    - SSL_SELF_SIGNED=false

    - GITLAB_HOST=gitlab
    - GITLAB_PORT=80
    - GITLAB_SSH_PORT=22
    - GITLAB_RELATIVE_URL_ROOT=
    - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string

    - GITLAB_ROOT_PASSWORD=12345678
    - GITLAB_ROOT_EMAIL=

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=notifications@example.com
    - GITLAB_EMAIL_REPLY_TO=noreply@example.com
    - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com

    - GITLAB_BACKUP_SCHEDULE=daily
    - GITLAB_BACKUP_TIME=01:00

    - SMTP_ENABLED=false
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_STARTTLS=false

    - OAUTH_ENABLED=false
    - OAUTH_AUTO_SIGN_IN_WITH_PROVIDER=
    - OAUTH_ALLOW_SSO=
    - OAUTH_BLOCK_AUTO_CREATED_USERS=true
    - OAUTH_AUTO_LINK_LDAP_USER=false
    - OAUTH_AUTO_LINK_SAML_USER=false
    - OAUTH_EXTERNAL_PROVIDERS=

    - OAUTH_CAS3_LABEL=cas3
    - OAUTH_CAS3_SERVER=
    - OAUTH_CAS3_DISABLE_SSL_VERIFICATION=false
    - OAUTH_CAS3_LOGIN_URL=/cas/login
    - OAUTH_CAS3_VALIDATE_URL=/cas/p3/serviceValidate
    - OAUTH_CAS3_LOGOUT_URL=/cas/logout

    - OAUTH_GOOGLE_API_KEY=
    - OAUTH_GOOGLE_APP_SECRET=
    - OAUTH_GOOGLE_RESTRICT_DOMAIN=

    - OAUTH_FACEBOOK_API_KEY=
    - OAUTH_FACEBOOK_APP_SECRET=

    - OAUTH_TWITTER_API_KEY=
    - OAUTH_TWITTER_APP_SECRET=

    - OAUTH_GITHUB_API_KEY=
    - OAUTH_GITHUB_APP_SECRET=
    - OAUTH_GITHUB_URL=
    - OAUTH_GITHUB_VERIFY_SSL=

    - OAUTH_GITLAB_API_KEY=
    - OAUTH_GITLAB_APP_SECRET=

    - OAUTH_BITBUCKET_API_KEY=
    - OAUTH_BITBUCKET_APP_SECRET=

    - OAUTH_SAML_ASSERTION_CONSUMER_SERVICE_URL=
    - OAUTH_SAML_IDP_CERT_FINGERPRINT=
    - OAUTH_SAML_IDP_SSO_TARGET_URL=
    - OAUTH_SAML_ISSUER=
    - OAUTH_SAML_LABEL="Our SAML Provider"
    - OAUTH_SAML_NAME_IDENTIFIER_FORMAT=urn:oasis:names:tc:SAML:2.0:nameid-format:transient
    - OAUTH_SAML_GROUPS_ATTRIBUTE=
    - OAUTH_SAML_EXTERNAL_GROUPS=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_EMAIL=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_NAME=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_FIRST_NAME=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_LAST_NAME=

    - OAUTH_CROWD_SERVER_URL=
    - OAUTH_CROWD_APP_NAME=
    - OAUTH_CROWD_APP_PASSWORD=

    - OAUTH_AUTH0_CLIENT_ID=
    - OAUTH_AUTH0_CLIENT_SECRET=
    - OAUTH_AUTH0_DOMAIN=

    - OAUTH_AZURE_API_KEY=
    - OAUTH_AZURE_API_SECRET=
    - OAUTH_AZURE_TENANT_ID=

  runner:
    restart: always
    image: 366857391347.dkr.ecr.eu-west-1.amazonaws.com/runner:a00b5e
    depends_on:
      - gitlab
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CI_SERVER_URL=http://charles:8000/ci/
      - RUNNER_EXECUTOR=docker
      - DOCKER_TLS_VERIFY=false
      - DOCKER_PRIVILEGED=false
      - DOCKER_DISABLE_CACHE=false
      - DOCKER_VOLUMES=/cache

  screenshotter:
    image: 366857391347.dkr.ecr.eu-west-1.amazonaws.com/screenshotter:37_176a24
    environment:
      - PORT=80

  gitsyncer:
    image: 366857391347.dkr.ecr.eu-west-1.amazonaws.com/git-syncer:7e2e65
    environment:
      - DEBUG=1
      - PORT=80
    ports:
      - "8006:80"

  charles:
    build: .
    depends_on:
      - gitlab
    ports:
      - "8000:8000"
    networks:
      default:
        aliases:
         - charles.local
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - GITLAB_HOST=gitlab
      - GITLAB_PORT=80
      - DB_ADAPTER=postgresql
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=gitlab
      - DB_PASS=password
      - DB_NAME=gitlabhq_production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SYSTEMHOOK_BASEURL=http://charles:8000
      - EXTERNAL_BASEURL=http://localtest.me:8000
      - MINARD_UI_BASEURL=http://localhost:3000
      - AUTH_COOKIE_DOMAIN=http://localtest.me
      - SCREENSHOT_URL_PATTERN=http://minard-%s.deployment.charles.internal:8000
      - SCREENSHOTTER_BASEURL=http://screenshotter
      - DEPLOYMENT_URL_PATTERN=http://%s.deployment.localtest.me:8000
      - EXTERNAL_GIT_BASEURL=http://git.localtest.me:8000
      - GITLAB_ROOT_PASSWORD=12345678
      - SENTRY_DSN=$SENTRY_DSN
      - ADMIN_ID=9A0cjUjLPIAIP52xTTWvuakblphA8EYu
      - OPEN_TEAM_NAMES=integrationtestopenteam
      - GIT_SYNCER_BASEURL=http://gitsyncer
      - GITHUB_TOKENS=${GITHUB_TOKENS}
      - EXIT_DELAY=0
      - DEBUG=1
