version: '2'

services:

  runner:
    build:
      context: ../gitlab-ci-multi-runner
      dockerfile: Dockerfile-lucify
    volumes:
        - ../gitlab-ci-multi-runner/docker-entrypoint.sh:/docker-entrypoint.sh


