FROM node:8.1-alpine

WORKDIR /code

COPY package.json /code/package.json

RUN npm install

ENV NODE_ENV production

COPY . /code
RUN npm run transpile
RUN npm prune && rm -rf src

# NOTE: don't use npm here since the OS signals, e.g. SIGTERM, won't propagate
# (read https://github.com/yelp/dumb-init for more)
CMD ["node", "dist/app.js"]
