FROM node:8.1-alpine
RUN echo #### Remember to transpile before building! ####
WORKDIR /code

COPY package.json /code/package.json
COPY yarn.lock /code/yarn.lock
ENV NODE_ENV production
RUN yarn install --prod

# NOTE: 'dist/' is assumed to contained the latest transpiled code
COPY . /code

# NOTE: don't use npm here since the OS signals, e.g. SIGTERM, won't propagate
# (read https://github.com/yelp/dumb-init for more)
CMD ["node", "dist/app.js"]
