version: '2'

services:
  redis:
    volumes:
    - ./gitlab-data/redis:/var/lib/redis:Z

  postgresql:
    volumes:
    - ./gitlab-data/postgresql/pgdata:/var/lib/postgresql/data/pgdata:Z

  gitlab:
    volumes:
    - ./gitlab-data/gitlab:/home/git/data:Z

  runner:
    volumes:
        - ./gitlab-data/runner:/etc/gitlab-runner
    environment:
      - DOCKER_IMAGE=node
      - DOCKER_NETWORK_MODE=minardbackend_default

  charles:
    build: .
    command: ["npm", "run", "dev"]
    ports:
      - "5858:5858"
      - "9229:9229"
    volumes:
      - ./gitlab-data/charles/deployments:/deployments
      - ./gitlab-data/charles/screenshots:/screenshots
      - ./migrations:/code/migrations
      - ./typings:/code/typings
      - ./src:/code/src
      - ./dist:/code/dist
      - ./tsconfig.json:/code/tsconfig.json
      - ./package.json:/code/package.json
    environment:
      - DEPLOYMENT_FOLDER=/deployments/
      - SCREENSHOT_FOLDER=/screenshots/

  screenshotter:
    depends_on:
      - bind
    volumes:
      - ./gitlab-data/charles/screenshots:/screenshots
    environment:
      - DEBUG=1
      - DNS_HOSTNAME=bind.local

  bind:
    image: cosmicq/docker-bind
    networks:
      default:
        aliases:
         - bind.local
    volumes:
      - ./gitlab-data/bind/etc:/etc/bind
      - ./gitlab-data/bind/zones:/var/lib/bind
    environment:
      - PASS=newpass
    logging:
      driver: none
