FROM mhart/alpine-node:latest

WORKDIR /code

COPY package.json /code/package.json

RUN npm install -g typescript@beta
RUN npm install && npm ls

ENV NODE_ENV production

COPY . /code
RUN npm run transpile
RUN npm prune


CMD ["npm", "start"]