#!/bin/bash

PROJECT=${SYSTEM_TEST_PROJECT:-"blank"}
if [[ -n "$1" ]]; then
  PROJECT="$1"
fi
FOLDER=src/integration-test/$PROJECT

echo "Folder is $FOLDER"

rm -rf $FOLDER/.git
git -C $FOLDER init
git -C $FOLDER config user.email foo@bar.com
git -C $FOLDER config user.name 'Foo Bar'
git -C $FOLDER add -A .
git -C $FOLDER commit -m 'Improve colors and styling'
