#!/bin/bash

set -e

echo "Running system integration tests. Service logs are available at /tmp/system-test-compose.log"

./compose-all > /tmp/system-test-compose.log 2>&1 &
npm run-script system-test-mocha
docker-compose down

echo "System integration tests finished"
