#!/bin/bash

set -e

echo "Running system integration tests. Service logs are available at /tmp/system-test-compose.log"

rm -f gitlab-data/runner/config.toml
docker-compose down
docker-compose up -d
npm run-script system-test-mocha
docker-compose down

echo "System integration tests finished"
